### ISSUE TITLE
Feature Structures in non-default views are not serialized to XMI

### ISSUE THREAD

**Issue by reneverheij** [dkpro/dkpro-cassis#102]
**Describe the bug**
While deserializing an XMI document produced by cassis, I get the following exception: 

> XCASParsingException: Error parsing XMI-CAS from source "<unknown"> at line 2, column 187427: xmi id 609 is referenced but not defined."

This exception is raised by an application that uses Apache UIMA version 2.10.0. The XMI contains a reference to XMI ID 609 in the members attribute of the cas:View element. There is no element in the XMI with this xmi:id.
`<cas:View sofa="608" members="609"/>`
[doc7.zip](https://github.com/dkpro/dkpro-cassis/files/3936554/doc7.zip)

**To Reproduce**
1. Import cas_in7.xml using load_cas_from_xmi()
2. Export the cas using to_xmi()

I have attached my input file as well as the output from to_xmi().

**Please complete the following information:**
 - Version: 0.2.6
 - OS: Windows 10
- IBM Watson Explorer v12 with Apache UIMA 2.10.0

**Comment by jcklie** [comment]
There are two `DocumentAnnotation` (one for each view), I thought there can be only one globally.

**Comment by reckart** [comment]
There can be one per view.

**Comment by reckart** [comment]
There could I think even be more than per view but only one has special meaning and having more than one per view is most likely a bug.

**Comment by jcklie** [comment]
After some investigation, I think it is a different error.

**Comment by jcklie** [comment]
@reneverheij I merged a fix in master, it would be nice if you could test it.

**Comment by reneverheij** [comment]
I can confirm that the error no longer occurs. When can I expect a release?
_Thank you very much for your support._

**Comment by jcklie** [comment]
I just released 0.2.7. I hope that cassis is now usable for you.
