### ISSUE TITLE
select_covered doesn't seem to work with base class

### ISSUE THREAD

**Issue by dmitriydligach** [dkpro/dkpro-cassis#104]
I'm evaluating the possibility of using CASSIS as a part of a cTAKES pipeline. I'm trying the script below. It works fine when I iterate over WordToken(s). However, select_covered() doesn't seem to find any BaseToken annotations. BaseToken is the super class of WordToken.

Here's the script:
```

  ts_file = open('TypeSystem.xml', 'rb')
  type_system = load_typesystem(ts_file)

  xmi_file = open('patientX_doc3_NOTE.txt.xmi', 'rb')
  cas = load_cas_from_xmi(xmi_file, typesystem=type_system)

  for sentence in cas.select('org.apache.ctakes.typesystem.type.textspan.Sentence'):
    print('\nsentence:', sentence.get_covered_text())

    # for token in cas.select_covered('org.apache.ctakes.typesystem.type.syntax.BaseToken', sentence):
    for token in cas.select_covered('org.apache.ctakes.typesystem.type.syntax.WordToken', sentence):
      print('token:', token.get_covered_text())
```

This script and the XMI/type system files are available here:

https://github.com/dmitriydligach/Sandbox/tree/master/PyCtakes

Note that the XMI file does not contain real patient data -- it is derived from a fake note.

P.S. Thanks again for creating this software -- it should be extremely useful when we get it to work!

**Comment by jcklie** [comment]
I did not realize that the `select*` methods also need to return instances of subtypes. I will add this soonish. Thanks for reporting! I hope we can get to a version of cassis which makes it suitable for your Ctakes.

**Comment by dmitriydligach** [comment]
@jcklie Thanks! And yes, UimaFit has this functionality and we routinely use this in cTAKES.

**Comment by reckart** [comment]
> UimaFit has this functionality

It is a feature for the core UIMA framework. uimaFIT just "inherits" it from the UIMA APIs that it wraps. 

Btw. if you are already using UIMAv3, you should have a look at the new select API it provides ;)

**Comment by jcklie** [comment]
This is a bit more intricate, I need to think about how to implement it while still being fast enough.

**Comment by dmitriydligach** [comment]
@jcklie Thank you very much. Please let me know if you need anything from me in the meantime.

**Comment by jcklie** [comment]
@dmitriydligach  I implemented it and it is in master. Can you have a quick test?

**Comment by dmitriydligach** [comment]
I installed from source (python3 setup.py install) and I'm happy to confirm that your fix works! @jcklie

**Comment by dmitriydligach** [comment]
@jcklie Thank you very much for fixing this issue. I'm not going to close it.
