### ISSUE TITLE
DKPro Typesystem XML not in pypi package

### ISSUE THREAD

**Issue by jcklie** [dkpro/dkpro-cassis#105]
**Describe the bug**
Just played around with this module (v0.2.7) and tried to use load_dkpro_core_typesystem() but it seems that "dkpro-core-types.xml" is absent from the PyPI package (see https://pypi.org/project/dkpro-cassis/#files), causing the function to tail. Adding in the XML file from the repo fixed it but you might want to look at this to make the released version work.

**Comment by jcklie** [comment]
Closed in #106

**Comment by ramonziai** [comment]
Still seems to be the case in the new release: https://files.pythonhosted.org/packages/44/45/cab32011f14f1163a40e478552180e8237d37df098a3d98598be6b7bbb31/dkpro-cassis-0.2.8.tar.gz

**Comment by jcklie** [comment]
Sorry for that, please try again.

**Comment by ramonziai** [comment]
Working now, thanks!
