### ISSUE TITLE
Type system deserializer does not strip whitespace when reading type names

### ISSUE THREAD

**Issue by ramonziai** [dkpro/dkpro-cassis#112]
**Describe the bug**
Following @jcklie's fix for #109, I tried loading a CAS with DKPro annotation types in it. Most of them appear to load fine, however I got the exception attached here:
[deserialization-error.txt](https://github.com/dkpro/dkpro-cassis/files/4147646/deserialization-error.txt)

I first looked for errors in the CAS I loaded but couldn't find anything wrong with it. Then I traced the problem to the included DKPro type system (dkpro-core-types.xml), where in the definition of `de.tudarmstadt.ukp.dkpro.core.api.segmentation.type.Token` the feature `morph` has a range type `de.tudarmstadt.ukp.dkpro.core.api.lexmorph.type.morph.MorphologicalFeatures`. In addition to the type name there is a trailing newline and some spaces for indentation, to make the XML more readable.
The current cassis type system deserializer apparently doesn't strip whitespace when reading type names, so I believe this is the problem here.

**To Reproduce**
1. Load the DKPro type system.
2. Load a CAS with an instance of the DKPro type `de.tudarmstadt.ukp.dkpro.core.api.segmentation.type.Token` in it.

Here's a minimal CAS that should trigger the issue: https://unitc-my.sharepoint.com/:u:/g/personal/nnszi01_cloud_uni-tuebingen_de/ETvi4vSFi_hBvbLX8FX5IEEBYmHjSCZR-ZnkD9bseiiuAg?e=w3dsOU

**Expected behavior**
Deserializer should ignore/strip whitespace so types can be identified as identical.

**Error message**
See https://github.com/dkpro/dkpro-cassis/files/4147646/deserialization-error.txt

**Please complete the following information:**
 - Version: 0.2.8.dev0
 - OS: Linux

**Additional context**

**Comment by jcklie** [comment]
Thanks for the reporting! It should be fixed soon. Apparently I never loaded a real CAS with this type system :(

**Comment by jcklie** [comment]
Should be fixed in master.

**Comment by ramonziai** [comment]
Record speed, thanks :-) Just tested, works. Closing issue.
