### ISSUE TITLE
Unpinned lxml dependency

### ISSUE THREAD

**Issue by danimarft** [dkpro/dkpro-cassis#118]
**Describe the bug**
I installed `dkpro-cassis` and couldn't get it to work because I had an incompatible (outdated) `lxml` library installed.
This was solved by updating to the latest version of `lxml` 
It would be nice to have pinned dependencies in the `setup.py` (at least to the major version)

**To Reproduce**
1. Have `lxml 3.4.1`
2. Try using the  `dkpro-cassis` library
3. `add_annotations()` function doesn't work 

**Expected behavior**
Everything works (because I have the latest ompatible `lxml` version)

**Please complete the following information:**
 - Version: 0.2.7
 - OS: Ubuntu

Thank you

**Comment by jcklie** [comment]
Thanks for reporting! I pinned all install dependencies, the fix will be in the next release.
