### ISSUE TITLE
cas.select_covered(some_type, some_sentence) is not working has expected when 2 or more annotations start at the beginning of the sentence.

### ISSUE THREAD

**Issue by LaurentBie** [dkpro/dkpro-cassis#144]
**Describe the bug**
cas.select_covered(some_type, some_sentence) is not working has expected when 2 or more annotations start at the beginning of the sentence. Only the last annotation that starts at the beginning of the sentence is returned.

**To Reproduce**
[error_dkpro_cassis.zip](https://github.com/dkpro/dkpro-cassis/files/5558945/error_dkpro_cassis.zip)

A solution would be to update the _get_feature_structures_in_range(...) method in the cas.py file. 
idx_begin = annotations.bisect_key_left((begin, begin)) 
idx_end = annotations.bisect_key_right((end, end))

**Comment by jcklie** [comment]
Thanks for the report! It will be fixed in the next release.
