### ISSUE TITLE
String in multipleReferencesAllowed is incorrectly parsed

### ISSUE THREAD

**Issue by DavidHuebner** [dkpro/dkpro-cassis#157]
**Describe the bug**
The String value `"false"` of the feature multipleReferencesAllowed is incorrectly parsed as `True`. 

The problem is in the function `_get_elem_as_bool(elem)` in `typesystem.py` where `bool(elem.text)` is called. For non-empty string values, this boolean is always True. We should use a slightly more advanced method to parse strings into booleans.

**To Reproduce**
1. Download a TypeSystem with multipleReferencesAllowed=false: https://raw.githubusercontent.com/apache/uima-ruta/main/ruta-typesystem/src/main/resources/org/apache/uima/ruta/engine/RutaInternalTypeSystem.xml
2. Execute

``` python
    with open('RutaInternalTypeSystem.xml', 'rb') as f:
        typesystem = load_typesystem(f)
    assert typesystem._types["org.apache.uima.ruta.type.DebugRuleElementMatches"]._features["inlinedActionBlocks"].multipleReferencesAllowed is False

```

**Expected behavior**
String value `"false"` should correctly be parsed as `False` (boolean).

**Error message**

**Please complete the following information:**
 - Version: 0.5.1
 - OS: Ubuntu 20.04

**Comment by jcklie** [comment]
Thanks for reporting! It should be fixed in master. I wait a bit in case you find more bugs, then I will release later this week. Is that an important bug/feature for you? I never understood nor used multipleReferencesAllowed.

**Comment by DavidHuebner** [comment]
Fantastic! Thanks again for your quick response. I encountered this problem when I deserialized/serialized a typesystem which was then incompatible with the original typesystem. I was not actually interested in the value of the multipleReferencesAllowed.

It is perfectly fine for now to work from the master branch / dev version. So, an immediate release is not needed. 

Thanks again!

**Comment by jcklie** [comment]
I released it, please have a try and close the bug when it works for you.
