### ISSUE TITLE
XMI is serialized using ASCII

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-cassis#165]
**Describe the bug**
It seems cassis by default serializes as ASCII but it should use UTF-8 instead.

**To Reproduce**
```
cas = Cas(TypeSystem())
print(cas.to_xmi())
```

**Expected behavior**
XMI should be serialized as UTF-8

**Please complete the following information:**
 - Version: 0.5.2

**Comment by reckart** [comment]
@jcklie didn't we have this issue with encoding recently already?

**Comment by jcklie** [comment]
Did you try it with 0.5.2 instead of 0.5.0?

**Comment by reckart** [comment]
GitHub says that 0.5.0 is the latest release?

**Comment by reckart** [comment]
I did a `pip install --upgrade dkpro-cassis` and it says that 0.5.2 is installed already, run the code and get the ASCII.

**Comment by reckart** [comment]
Fixed in 0.5.3.
