### ISSUE TITLE
Typo in documentation? cas.xml => cas.xmi

### ISSUE THREAD

**Issue by zesch** [dkpro/dkpro-cassis#251]
all the examples in the core documentation say `with open('cas.xml', 'rb')`. Shouldn't it be 'xmi' instead of 'xml'?

**Comment by reckart** [comment]
Yes, I think you are right. `.xml` is usually used for the type system and `.xmi` for the CAS XMI files.

**Comment by jcklie** [comment]
Thanks for the report, I fixed it.
