### ISSUE TITLE
unexpected output when reading DKPro .xmi

### ISSUE THREAD

**Issue by zesch** [dkpro/dkpro-cassis#252]
**Describe the bug**
I have created an xmi with Java DKPro and I am now trying to read that back in using Cassis. When trying to access and print some annotations, I get some kind of (infinite?) loop that outputs GB of what looks like type descriptions.

**To Reproduce**
run attached main.py 

If possible, attach a minimal file that triggers the error. 

**Please complete the following information:**
 - Version: 0.7.0
 - OS: OS [X](url)

 - 
[Archive.zip](https://github.com/dkpro/dkpro-cassis/files/8333243/Archive.zip)

**Comment by jcklie** [comment]
Thanks for the report, I shortened the output a bit.
