### ISSUE TITLE
Unexpected modification of existing document?

### ISSUE THREAD

**Issue by WeaponXiii** [dkpro/dkpro-cassis#30]
It looks like cassis is omitting existing XML namespace attributes. Also, it's rewriting xmi:id attribute of preexisting XML Nodes. Is this resulting from getting rid of some form of redundant information? Or is this a bug?

Take a look at the attached documents

[prediction.zip](https://github.com/dkpro/dkpro-cassis/files/2581834/prediction.zip)

**Comment by WeaponXiii** [comment]
Ok, I got that now. But what about dropping some namespace information. For instance, the request CAS had  xmlns:pos, xmlns:morph etc. but in response CAS it doesn't have such information. Is that also permitted?

**Comment by reckart** [comment]
IMHO yes because if a namespace is not referenced in an XML file, there is no need to declare it. Note that the actual type system information is not contained in the XMI anyway - it is in the separate typesystem description XML file. Without the typesystem description XML file, the content of the XMI file is hardly interpretable.

**Comment by WeaponXiii** [comment]
Thanks for the info. It seems like I had a complete misunderstanding of the concept.

**Comment by reckart** [comment]
Quick example why an XMI cannot be properly interpreted without the typesystem description XML file:

* A numeric feature is represented e.g. as an attribute `num="1"`.
* A reference feature (i.e. a feature which points to another XML element in the XMI file) could also look like `someFooRef="1"`.

Without the information from the typesystem description XML file, you cannot tell if either of the attributes above is a numeric attribute or a reference.
