### ISSUE TITLE
How to prase event information annotation ? 

### ISSUE THREAD

**Issue by thetaaaaa** [dkpro/dkpro-cassis#320]
**Is your feature request related to a problem? Please describe.**

Here is some annotation for events in text , an event  annotation consists of event trigger word, event role and role type. With dkpro-cassis, I can only have access to the event trigger word's feature but have no way to have access to the element's feature. How am I suppose to do that ?  
![image](https://github.com/user-attachments/assets/e85b644a-0383-4f35-ba0c-58eb38bf2dc9)
**Describe the solution you'd like**
I want to have access to arguments and its elements(which are in u.c.FSArray) and their text through the feature of w.c.Trigger in my case. Thank you.
**Describe alternatives you've considered**

**Additional context**

**Comment by reckart** [comment]
Try 

```
for element in trigger.arguments.elements:
```

or 

```
for element in trigger.get('arguments').elements:
```

**Comment by thetaaaaa** [comment]
Both of them works, thanks ! 
![image](https://github.com/user-attachments/assets/c7933193-f647-415b-9e93-fa40bd23bc21)
