### ISSUE TITLE
Circular annotations

### ISSUE THREAD

**Issue by GregSilverman** [dkpro/dkpro-cassis#40]
Spoke too soon. Both cTAKES and Clamp both have circular annotations (or linked, if you want to get pedantic).

Getting the following error:

```
---------------------------------------------------------------------------
CircularDependencyError                   Traceback (most recent call last)
<ipython-input-4-ff102eb39ae5> in <module>()
      7 dir_test = '/Users/gms/development/nlp/nlpie/data/medinfo/ctakes_out/'
      8 with open(dir_test + 'TypeSystem.xml', 'rb') as f:
----> 9     typesystem = load_typesystem(f)
     10     #print(dir(typesystem))
     11     #print(typesystem.get_types())

/anaconda3/lib/python3.7/site-packages/cassis/typesystem.py in load_typesystem(source)
    425         return deserializer.deserialize(BytesIO(source.encode("utf-8")))
    426     else:
--> 427         return deserializer.deserialize(source)
    428 
    429 

/anaconda3/lib/python3.7/site-packages/cassis/typesystem.py in deserialize(self, source)
    482 
    483         ts = TypeSystem()
--> 484         for type_name in toposort_flatten(dependencies, sort=False):
    485             # No need to create predefined types
    486             if type_name in PREDEFINED_TYPES:

/anaconda3/lib/python3.7/site-packages/toposort.py in toposort_flatten(data, sort)
     88 
     89     result = []
---> 90     for d in toposort(data):
     91         result.extend((sorted if sort else list)(d))
     92     return result

/anaconda3/lib/python3.7/site-packages/toposort.py in toposort(data)
     79                     if item not in ordered}
     80     if len(data) != 0:
---> 81         raise CircularDependencyError(data)
     82 
     83 

CircularDependencyError: Circular dependencies exist among these items: {'org.apache.ctakes.typesystem.type.textsem.SemanticArgument':{'org.apache.ctakes.typesystem.type.textsem.SemanticRoleRelation'}, 'org.apache.ctakes.typesystem.type.textsem.SemanticRoleRelation':{'org.apache.ctakes.typesystem.type.textsem.SemanticArgument'}}
```

These are definitely legit, and can be viewed in the UIMA CVD. 

Any ideas on how to implement, and I will do the work. Again, I could just remove these annotations, especially since we are not interested in them, but when dealing with 50 million x 2 files, that is a lot of processing time. 

Worst case, we can modify the AE config file to not print these as output.

**Comment by reckart** [comment]
For any of the cases you reported, it would be good to have sample files so we can easily reproduce the problem and test.

**Comment by reckart** [comment]
We would also happily be accepting pull requests with fixes. Your priorities might allow you to look into fixes in a more timely manner than our priorities allow us.

**Comment by jcklie** [comment]
The problem is that cassis resolves inheritance in the type system by topological sort over the inheritance graph, and that is not working with circular inheritance. I would need to see the typesystem for a more educated guess though.

**Comment by reckart** [comment]
Are we facing a circular inheritance or reference? 

I'm pretty sure that circular inheritance would be a mistake in the type system and would cause errors in UIMA as well. 

But it is well valid that two types refer to each other, e.g. by declaring features of the respective other type.

**Comment by GregSilverman** [comment]
This is referential. For the short term I will disable this check. I will also shoot you the TypeSystem file  in due course. (I know I am bombarding you with issues!)

**Comment by GregSilverman** [comment]
Here's a CAS and TypeSystem definition for circular reference. To move forward, I changed the definition in the TypeSystem file to be `String`, since I don't care about these annotations.
[ctakes_out.zip](https://github.com/dkpro/dkpro-cassis/files/2846317/ctakes_out.zip)

As always, thanks for the prompt response.

**Comment by jcklie** [comment]
I tried your file and cannot reproduce that error in master. Did you already adjust it to work?

**Comment by GregSilverman** [comment]
I must have sent you the wrong TypeSystem file. Let's close this for now, especially since, at this time, I don't need the annotations for these types.
