### ISSUE TITLE
Support types with no namespace

### ISSUE THREAD

**Issue by jcklie** [dkpro/dkpro-cassis#43]
**Is your feature request related to a problem? Please describe.**
Some UIMA CAS handling frameworks define type systems with types that have no namespace, e.g. 

        <typeDescription>
            <name>ArtifactID</name>
            <description>A unique artifact identifier.</description>
            <supertypeName>uima.cas.TOP</supertypeName>
            <features>
                <featureDescription>
                    <name>artifactID</name>
                    <description>A unique identification string for the artifact. This should be the file name for files,
            or the unique identifier used in a database if the document source is a database
            collection reader.</description>
                    <rangeTypeName>uima.cas.String</rangeTypeName>
                </featureDescription>
            </features>
        </typeDescription>

**Describe the solution you'd like**
When importing these types, prefix their name with `uima.noNamespace.` This is apparently how it was done in the past.

**Describe alternatives you've considered**
Not supporting this, but it does not cost much and supports old systems.

**Comment by reckart** [comment]
Where does this `uima.noNamespace.` actually come from?

**Comment by jcklie** [comment]
From the CAS namespace.

**Comment by reckart** [comment]
Looking at the UIMA source code, this seems to be a specific thing of the XMI serialization. When parsing the deserializing the XMI, this is dropped. I think it would be good if cassis did the same thing.

**Comment by jcklie** [comment]
It looks like we can handle this, I will reopen this issue in case of new problems.
