### ISSUE TITLE
Inconsistent xmiID

### ISSUE THREAD

**Issue by GregSilverman** [dkpro/dkpro-cassis#48]
**Describe the bug**

`xmiID` is getting changed somewhere along the way.

**To Reproduce**

Add the following line to the end of _parse_annotations:

```
if attributes["xmiID"] == 52613:

            print("TEST:", attributes)
```

With included XMI and Typesystem files, run the following:

```
with open(dir_test + 'TypeSystem.xml', 'rb') as f:
    typesystem = load_typesystem(f)
    
fname = '737-v1.txt.xmi'
with open(dir_test + fname, 'rb') as f:
    cas = load_cas_from_xmi(f, typesystem=typesystem)

view = cas.get_view('Analysis')

print([x for x in view.select("biomedicus.v2.UmlsConcept")])
```

You will see:

```
TEST: {'sofa': 18, 'begin': 10, 'end': 14, 'sui': 'S0628538', 'cui': 'C2740799', 'tui': 'T121', 'source': 'MTHSPL', 'confidence': '1.0', 'xmiID': 52613}
[biomedicus_v2_UmlsConcept(xmiID=9826, sui='S0628538', cui='C2740799', tui='T121', source='MTHSPL', confidence='1.0', begin=10, end=14, sofa=6, type='biomedicus.v2.UmlsConcept')...]
```

The `xmiID`s are not the same (they should be, since they are the first set of annotations for this type).

**Expected behavior**

Expect the output `xmiID` to not change. 

I suspect this has something to do with the AnnotationBase class definition, but have not had a chance to examine this further.

**Please complete the following information:**
 - Version: 0.2.0.dev0
 - OS: MacOS

[Archive.zip](https://github.com/dkpro/dkpro-cassis/files/2871318/Archive.zip)

**Comment by jcklie** [comment]
XMI ids are internal IDs and even in Java by default are not kept over importing -> exporting.

**Comment by GregSilverman** [comment]
What about the case when the xmiID is used for linking to another annotation type?

**Comment by jcklie** [comment]
The ids are consistent inside a document. Both would change to stay in sync.

**Comment by GregSilverman** [comment]
The ids are actually listed in an array with a different name. For example, the array is named `ontologyConceptArr` and has the original `xmiID`s listed.  These did not change to stay in sync, and thus the mapping got lost.

**Comment by jcklie** [comment]
Ah, sry. We need to change that. Before the reference support from you, I never touched these ids so I overlooked that issue. Thank you for reporting!

**Comment by GregSilverman** [comment]
Hi, if you could give me an idea of how to implement this where the xml:id gets used like other attributes, I can try to modify the code. 

I'm thinking it would be good to have a switch where the user can specify if they want to use the default auto incremented id, or to use the one as given in the original CAS XMI. This is rather critical for our current experiment, since we need to resolve the relational mappings.

**Comment by reckart** [comment]
In the core UIMA framework, references between feature structures are essentially turned into object references on import. And when the data is exported again to XMI, then new IDs are generated as part of the export process. If users need stable IDs for feature structures (beyond the need of modelling object references) across import/export, the idea is usually that they add a "id" feature to the type system.

**Comment by GregSilverman** [comment]
Thanks for the explanation. It makes sense.  With that, I was able to add a kludge for this. I added `id` as a feature to the type in question and under `_parse_annotations,` I added the conditional:

```
 if typename == "org.apache.ctakes.typesystem.type.refsem.UmlsConcept": # linked feature type 
            attributes["id"] = int(attributes["xmiID"])

```

I did try a more general solution of if `"id" in attributes`, but for some reason that did not work.
