### ISSUE TITLE
Add test files from uimaj

### ISSUE THREAD

**Issue by jcklie** [dkpro/dkpro-cassis#49]
It would be nice to add the test files that UIMA uses to the cassis test suite. 
Tests can be found under e.g. https://github.com/apache/uima-uimaj/blob/a68b57a8eaca2ee5392903d8f2f86bca5df08054/uimaj-core/src/test/java/org/apache/uima/cas/impl/XmiCasDeserializerTest.java

Files can e.g. be found under 
https://github.com/apache/uima-uimaj/tree/a68b57a8eaca2ee5392903d8f2f86bca5df08054/uimaj-core/src/test/resources/ExampleCas

**Comment by reckart** [comment]
We have aligned the test files with the UIMA Java SDK.
