### ISSUE TITLE
Add basic sofa/view support

### ISSUE THREAD

**Issue by Rentier** [dkpro/dkpro-cassis#5]
- [x] Annotations  should be added to a CAS/sofa, instead of specifying sofa as a parameter.
- [x] Allow getting sofas from a CAS
- [ ] Documentation

**Comment by Rentier** [comment]
@reckart What is the difference between a view and a sofa?

**Comment by reckart** [comment]
@Rentier good question. A CAS may contain multiple SofAs - each representing one text or other piece of primary data which is being annotated. When interacting with a CAS, one usually interacts with a "view" of the CAS which has a single SofA and which indexes all annotations that annotate this SofA. Annotations are a subtype of "feature structures". The SofA itself is a "feature structure". Annotations can only be indexed in one view and are always bound to a SofA. I believe feature structures could in theory be indexed in multiple views and they are not bound to a particular SofA.

I recommend reading these papers:

* [Design and implementation of the UIMA common analysis system](https://dl.acm.org/citation.cfm?id=1036176)
* [An Effective, Java-Friendly Interface to the CAS](https://pdfs.semanticscholar.org/bdbd/b5e71a71d2e023e806fb3e70fb4b6c50f30b.pdf)

**Comment by Rentier** [comment]
Still needs documentation
