### ISSUE TITLE
while deserializing xmi: AttributeError ... object has no attribute 'sofa 

### ISSUE THREAD

**Issue by Br0ce** [dkpro/dkpro-cassis#60]
deserializing xmi with myType and its supertypeName=`uima.cas.TOP`
an AttributeError: myType object has no attribute 'sofa'
...
/cassis/cas.py", line 169, in add_annotation
    annotation.sofa = self.get_sofa().xmiID

is raised.

(Please note that processing xmi in java is not an issue)

**Comment by jcklie** [comment]
Hello,
thank you for using cassis and reporting this isse. Can you tell me which version you are using and send me a minimal typesystem and CAS which triggers the bug?

**Comment by reckart** [comment]
`uima.cas.TOP` doesn't have a feature called `sofa` - it is only introduced by `uima.cas.AnnotationBase`.

**Comment by Br0ce** [comment]
Thx for fast reply,

I will assemble a minimal typesystem.

Meanwhile, with regard to @reckart, it should not be an AttributeError, that Type `uima.cas.TOP` doesn't have an attribute `sofa`.

( In this case, as far as I can see, in `Cas.add_annotations`
`if hasattr(annotation, "sofa"):` should be `False` )

**Comment by Br0ce** [comment]
Hi @jcklie,
I'm using dkpro-cassis version 0.1.1.
Attached to this post is a TypesSystem and a XMI (extended filename by .txt to support upload).
Deserializing the XMI raises the AttributeError.
Thx
[TypeSystem.xml.txt](https://github.com/dkpro/dkpro-cassis/files/3405718/TypeSystem.xml.txt)
[Example.cas.xmi.txt](https://github.com/dkpro/dkpro-cassis/files/3405723/Example.cas.xmi.txt)

**Comment by jcklie** [comment]
In[ 0.2.0-rc1](https://pypi.org/project/dkpro-cassis/0.2.0rc1/), this works for me except that you redefine `DocumentAnnotation`, which I need to fix (see #12).

**Comment by Br0ce** [comment]
Ah, ok. All good now.
Thank you.

**Comment by jcklie** [comment]
I will fix #12 this week or so and then you can try the next release candidate.

**Comment by Br0ce** [comment]
appreciate!
