### ISSUE TITLE
XMI serialising throws if CAS contains reference to empty array

### ISSUE THREAD

**Issue by geniki** [dkpro/dkpro-cassis#70]
**Describe the bug**
I exported a simple test case from WebAnno 3.6 (no custom tags, only the default ones from WebAnno), which I read using `cassis`. Trying to serialise it again results in an error.

**To Reproduce**
```
from cassis import *

path = "path/to/test_case/"

with open(path + '/TypeSystem.xml', 'rb') as f:
    typesystem = load_typesystem(f)

with open(path + '/test_file.xmi', 'rb') as f:
    cas = load_cas_from_xmi(f, typesystem=typesystem)

serialised = cas.to_xmi(path=None)
```

If possible, attach a minimal file that triggers the error. 
[webanno_test_case.zip](https://github.com/dkpro/dkpro-cassis/files/3750843/webanno_test_case.zip)

**Expected behavior**
Serialised file returned without errors.

**Error message**
```
  File "<ipython-input-5-cf0db0819547>", line 12, in <module>
    serialised= cas.to_xmi(path=None)
  File "..../dkpro-cassis/cassis/cas.py", line 333, in to_xmi
    serializer.serialize(sink, self, pretty_print=pretty_print)
  File ".../dkpro-cassis/cassis/xmi.py", line 243, in serialize
    for annotation in sorted(self._find_all_fs(cas), key=lambda a: a.xmiID):
  File ".../dkpro-cassis/cassis/xmi.py", line 276, in _find_all_fs
    for referenced_fs in lst:
TypeError: 'NoneType' object is not iterable
```
**Please complete the following information:**
 - Version: 0.2.1
 - OS: Ubuntu 18 and MacOS

**Additional context**
Similar situation to [#64](https://github.com/dkpro/dkpro-cassis/issues/64) but with a different test case.

**Comment by jcklie** [comment]
Thank you for the report! I can reproduce the error and will have a look. Btw, you do not need `path=None` when serialising.

**Comment by jcklie** [comment]
It should be fixed in master, I will try to release a new version this or next week. You can just use the master via pip using ` python -m pip install git+https://github.com/dkpro/dkpro-cassis`
