### ISSUE TITLE
Error when reading XMI files with sofaURI

### ISSUE THREAD

**Issue by dmitriydligach** [dkpro/dkpro-cassis#79]
I'm trying to read one of my XMI files that I've always been able to read successfully in the past using Java UimaFit tools. I run the following code:

```
  ts_file = open('TypeSystem.xml', 'rb')
  type_system = load_typesystem(ts_file)
```

```
  xmi_file = open('/Users/Dima/Loyola/Data/Thyme/Xmi/ID169_clinic_496.xmi', 'rb')
  cas = load_cas_from_xmi(xmi_file, typesystem=type_system)
```

and I get this error:

```
Traceback (most recent call last):
  File "./cas.py", line 11, in <module>
    cas = load_cas_from_xmi(xmi_file, typesystem=type_system)
  File "/usr/local/lib/python3.6/site-packages/cassis/xmi.py", line 38, in load_cas_from_xmi
    return deserializer.deserialize(source, typesystem=typesystem)
  File "/usr/local/lib/python3.6/site-packages/cassis/xmi.py", line 71, in deserialize
    sofa = self._parse_sofa(elem)
  File "/usr/local/lib/python3.6/site-packages/cassis/xmi.py", line 188, in _parse_sofa
    return Sofa(**attributes)
TypeError: __init__() got an unexpected keyword argument 'sofaURI'
```

Any thoughts what's causing it? Thank you very much in advance.

**Comment by jcklie** [comment]
Can you give me a minimal xmi and typesystem that fails?

**Comment by dmitriydligach** [comment]
I can give you the typesystem if it helps, but unfortunately I can't give you the XMI files (it has patient information)...

**Comment by jcklie** [comment]
Can you give me a xmi which only contains the sofa? I need to see the attributes on there, the sofa text can be removed.

**Comment by jcklie** [comment]
I assume that the problem is that your xmi uses a sofa with `sofaURI`. I did not have an example for what that implies, therefore I did not implement it. Are the annotations in the xmi or in a different file? If they are in the same file, you could just try to remove that attribute.

**Comment by dmitriydligach** [comment]
HI Jan-Christoph. I will think about a way to remove the text from these XMIs tomorrow (sorry, I've never looked at the XMI files directly -- I always relied on UimaFit to read them). 

These XMI files have multiple views (_InitialView, UriView, and GoldView -- which stores manual annotations). I'll see if I can find the Java code that was used to generated these XMI files.

Thanks for your help.

**Comment by jcklie** [comment]
I looked around a bit, maybe is enough to know whether the views have `sofaURI` and `sofaString` or just `sofaURI`. Is the text you annotated outside of your XMI?

**Comment by reckart** [comment]
@dmitriydligach after you have loaded them with uimaFIT, how do you access the document text - or do you not access it at all?

**Comment by reckart** [comment]
AFAIK sofaString and sofaURI are mutually exclusive.

**Comment by dmitriydligach** [comment]
@jcklie @reckart Maybe it would be useful to give you some sample code that I've used to access the annotations in these XMI files:

https://svn.apache.org/repos/asf/ctakes/trunk/ctakes-temporal/src/main/java/org/apache/ctakes/temporal/data/analysis/GoldRelationViewer.java

And yes, the document text is in the XMIs. I access it by something like:

timeMention.getCoveredText()

I hope this helps!

**Comment by dmitriydligach** [comment]
It might also be helpful for you to see the code that was used to generated these XMIs:

https://svn.apache.org/repos/asf/ctakes/trunk/ctakes-temporal/src/main/java/org/apache/ctakes/temporal/eval/Evaluation_ImplBase.java

**Comment by reckart** [comment]
Ok, so if I understand the ClearTK code correctly....

* they maintain a special view called `UriView` in the CAS which has it's `sofaURI` pointing to some URL
* when loading a CAS from somewhere, they do *not* set the text of the `_defaultView` directly, but instead look at the `UriView`, obtain the text from the URL specified there and *then* set this text into the `_defaultView`.

This is not a UIMA or uimaFIT thing - this is a ClearTK special behavior.

cassis should be able to parse the XMI from cTAKES/ClearTK, but the responsibility for obtaining resolving the URL in the `UriView` and using its content to set the text in the `_defaultView` is something that would seem to me to be outside the scope of cassis. It would need to be done in client code after the XMI has been read.

**Comment by jcklie** [comment]
The error you get should be fixed in master, I will try to release a new version this or next week. You can just use the master via pip using `python -m pip install git+https://github.com/dkpro/dkpro-cassis`

The issue is that your code does some non-standard things. If you load the XMI without any changes into cassis, then you might not have any text. I think that you need to get the sofaURI from your uriView, get the text via urllib or so and then set it as the sofaText on the InitialView.

**Comment by dmitriydligach** [comment]
@jcklie Thank you very much again for looking into this issue. 

I performed the following steps:

1. pip install git+https://github.com/dkpro/dkpro-cassis
2.   ts_file = open('TypeSystem.xml', 'rb')
      type_system = load_typesystem(ts_file)
      xmi_file = open('<my local path>/ID169_clinic_496.xmi', 'rb')
      cas = load_cas_from_xmi(xmi_file, typesystem=type_system)

I get the following error:

Traceback (most recent call last):
  File "./cas.py", line 11, in <module>
    cas = load_cas_from_xmi(xmi_file, typesystem=type_system)
  File "/usr/local/lib/python3.6/site-packages/cassis/xmi.py", line 38, in load_cas_from_xmi
    return deserializer.deserialize(source, typesystem=typesystem)
  File "/usr/local/lib/python3.6/site-packages/cassis/xmi.py", line 111, in deserialize
    fs = self._parse_feature_structure(typesystem, elem, children)
  File "/usr/local/lib/python3.6/site-packages/cassis/xmi.py", line 219, in _parse_feature_structure
    return AnnotationType(**attributes)
  File "/usr/local/lib/python3.6/site-packages/cassis/typesystem.py", line 187, in __call__
    return self._constructor(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'id'

**Comment by jcklie** [comment]
It looks like your annotation contains a field `id` which is not defined in the typesystem. Sadly I cannot tell you more  without a minimal CAS and typesystem. If you cannot give me the XMI, then can you attach a debugger in pycharm, set an[ breakpoint on exceptions ](https://stackoverflow.com/questions/5839286/break-on-unhandled-exception-in-pycharm)and tell me on which annotation it breaks? Then I would need the typesystem at least.

**Comment by reckart** [comment]
UIMA optionally supports "lenient" loading in which any features / types not in the type system are silently dropped. Might be good for cassis to support as well.

**Comment by dmitriydligach** [comment]
@jcklie Sorry, for the delay. I'm trying to figure out how to give you the XMI file. Please stay tuned. The type system is available here: https://svn.apache.org/repos/asf/ctakes/trunk/ctakes-type-system/src/main/resources/org/apache/ctakes/typesystem/types/TypeSystem.xml

**Comment by dmitriydligach** [comment]
@jcklie @reckart Apologies again for the delay. I see that you've made some nice improvements to dkpro-cassis. I just re-tested this issue. The original error is gone, however I get the error below.

Thank you very much in advance for your help!

Traceback (most recent call last):
  File "./cas.py", line 11, in <module>
    cas = load_cas_from_xmi(xmi_file, typesystem=type_system)
  File "/usr/local/lib/python3.6/site-packages/cassis/xmi.py", line 40, in load_cas_from_xmi
    return deserializer.deserialize(source, typesystem=typesystem)
  File "/usr/local/lib/python3.6/site-packages/cassis/xmi.py", line 77, in deserialize
    proto_view = self._parse_view(elem)
  File "/usr/local/lib/python3.6/site-packages/cassis/xmi.py", line 213, in _parse_view
    members = [int(e) for e in attributes.get("members", "").strip().split(" ")]
  File "/usr/local/lib/python3.6/site-packages/cassis/xmi.py", line 213, in <listcomp>
    members = [int(e) for e in attributes.get("members", "").strip().split(" ")]
ValueError: invalid literal for int() with base 10: ''

**Comment by jcklie** [comment]
@dmitriydligach  Do you have an actual XMI that I can test? It is else really difficult to debug.

**Comment by dmitriydligach** [comment]
@jcklie Sorry for the delay. We are working on creating an XMI files using fake data for you. We will likely have it for you this week. Please stay tuned.

**Comment by dmitriydligach** [comment]
@jcklie We created three XMI files using fake data that mimic our real XMI files. They contain three views: goldView, systemView(_initialView), and UriView. When I try to read them using:

  ts_file = open('TypeSystem.xml', 'rb')
  type_system = load_typesystem(ts_file)

  xmi_file = open('XmiMultViews/patientX_doc1_RAD.xmi', 'rb')

I get this error:

Traceback (most recent call last):
  File "./cas_mult_views.py", line 12, in <module>
    cas = load_cas_from_xmi(xmi_file, typesystem=type_system)
  File "/usr/local/lib/python3.6/site-packages/cassis/xmi.py", line 40, in load_cas_from_xmi
    return deserializer.deserialize(source, typesystem=typesystem)
  File "/usr/local/lib/python3.6/site-packages/cassis/xmi.py", line 131, in deserialize
    raise RuntimeError("Number of views and sofas is not equal!")
RuntimeError: Number of views and sofas is not equal!

You can look at these XMI files here:

https://github.com/dmitriydligach/Sandbox/tree/master/PyCtakes/XmiMultViews/

**Comment by jcklie** [comment]
@reckart Can a CAS have a different number of sofas and views? I thought they are 1:1 .

**Comment by reckart** [comment]
> Can a CAS have a different number of sofas and views? I thought they are 1:1 .

I though that as well. It is probably true anyway, but I think in these cases, the view annotation might not have been created (yet) because there is no annotation for the given sofa, e.g. on

```
<cas:Sofa xmi:id="1" sofaNum="2" sofaID="UriView" sofaURI="file:/Users/chenlin/Projects/temp/patientX_thyme/anafora_files/Train/ID001_path_002/ID001_path_002" />
```

Looks like the UIMA `org.apache.uima.cas.impl.XmiCasSerializer.XmiDocSerializer.writeView(Sofa, Collection<TOP>)` method only creates the `view` element in the XMI if there are annotations pointing to that Sofa (i.e. `membersString.length() > 0`):

```
        if (membersString.length() > 0) {
          XmlElementName elemName = uimaTypeName2XmiElementName("uima.cas.View");
          startElement(elemName, workAttrs, 0);
          endElement(elemName);
        }
```

**Comment by jcklie** [comment]
I added a fix to master for this. You can just use the master via `pip using python -m pip install git+https://github.com/dkpro/dkpro-cassis` . Please close this issue if it works for you.

**Comment by dmitriydligach** [comment]
Dear Jan-Christoph, thanks a lot for fixing this issue. I'm now able to read annotations from different views in the XMI files I provided! I will close this issue. @jcklie

**Comment by dmitriydligach** [comment]
@jcklie Sorry, before I close this, there's one more potential problem. Please let me know if you'd like me to close this issue and open a new one instead:

I try to read our real XMI files using the code that worked on the 'fake' XMIs above, but got this error. Unfortunately, I can't give you this XMI files, but is there something you can glean out of the error below?

/Users/Dima/Git/Sandbox/PyCtakes/>cas_mult_views.py
Traceback (most recent call last):
  File "./cas_mult_views.py", line 11, in <module>
    cas = load_cas_from_xmi(xmi_file, typesystem=type_system)
  File "/usr/local/lib/python3.6/site-packages/cassis/xmi.py", line 40, in load_cas_from_xmi
    return deserializer.deserialize(source, typesystem=typesystem)
  File "/usr/local/lib/python3.6/site-packages/cassis/xmi.py", line 77, in deserialize
    proto_view = self._parse_view(elem)
  File "/usr/local/lib/python3.6/site-packages/cassis/xmi.py", line 215, in _parse_view
    members = [int(e) for e in attributes.get("members", "").strip().split(" ")]
  File "/usr/local/lib/python3.6/site-packages/cassis/xmi.py", line 215, in <listcomp>
    members = [int(e) for e in attributes.get("members", "").strip().split(" ")]
ValueError: invalid literal for int() with base 10: '

**Comment by reckart** [comment]
```
members = [int(e) for e in attributes.get("members", "").strip().split(" ")]
ValueError: invalid literal for int() with base 10: '
```

Looks like it tries to cast a `'` into an int? Does the `members` attribute in all of the `view` elements in that XMI only contain numbers?

**Comment by dmitriydligach** [comment]
@reckart Sorry, do you mean things like

<cas:View sofa="8" members="15 7025 7031 7037 7043 ...

in the XMI file? If yes, I'm only seeing the numbers there...

**Comment by dmitriydligach** [comment]
@reckart Sorry, I don't think I pasted all of the error. It's '' rather ' at the end... So, there's an empty string somewhere it's trying to cast?

**Comment by jcklie** [comment]
Can you try to change the source code there to either 

`members = [int(e) for e in attributes.get("members", "").strip().split()]`

or 

`members = [int(e) for e in attributes.get("members", "").strip().split() if len(e)]`

You can just edit 

`/usr/local/lib/python3.6/site-packages/cassis/xmi.py` 

if you do not want to setup a development environment.

**Comment by dmitriydligach** [comment]
@jcklie Yes, this fixes the problem! Both solutions you suggested worked. Are you going to check in this update?

**Comment by jcklie** [comment]
@dmitriydligach I pushed it to master, you can have a try. If all goes well, then I release 0.2.8 this weekend or so.

**Comment by dmitriydligach** [comment]
@jcklie Yes, it works in master. Thanks!

One small issue though. Did you forget to remove a print statement somewhere? When I run my test script (https://github.com/dmitriydligach/Sandbox/blob/master/PyCtakes/cas_mult_views.py) after it prints the EventMention annotations, it prints a few types from the type system, e.g.:

...
Ultrasound guided core biopsy
suggestive
malignancy
org.apache.ctakes.typesystem.type.textsem.MedicationMention
org.apache.ctakes.typesystem.type.textsem.DiseaseDisorderMention
org.apache.ctakes.typesystem.type.textsem.MedicationEventMention
org.apache.ctakes.typesystem.type.textsem.ProcedureMention
org.apache.ctakes.typesystem.type.textsem.SignSymptomMention
org.apache.ctakes.typesystem.type.textsem.LabMention

**Comment by jcklie** [comment]
Try again, sorry .

**Comment by dmitriydligach** [comment]
@jcklie All good now, thanks! I'll close the issue. 

Thanks again for all your help with addressing the problems I raised. I'll keep experimenting with cassis (it looks extremely useful!) and let you know if I run into other issues.
