### ISSUE TITLE
Make creating type classes lazy

### ISSUE THREAD

**Issue by jcklie** [dkpro/dkpro-cassis#84]
**Is your feature request related to a problem? Please describe.**
Right now, when loading a typesystem, all Python classes representing types in the type system are created, whether they will be used later or not. This is slow for large type systems.

**Describe the solution you'd like**
Make it possible to create a type class when creating an annotation of that type for the first time.

**Comment by reckart** [comment]
Is this a performance optimization?

**Comment by jcklie** [comment]
Yes

**Comment by jcklie** [comment]
Should be ok done.
